### ISSUE TITLE
Map function to slices with index labels

### ISSUE THREAD

**Issue by Lincoln-Hannah** [mcabbott/AxisKeys.jl#158]
Ability to map a function to slices of a KeyedArray including the dimension index names of each slice. 
Proposed syntax below passes the slice and index names as a named tuple.

```
function my_func(  (; slice, I, X )  )

    "$I  $X    $(slice(:a))"

end

K  =   KeyedArray(   [1;2;;3;4;;;5;6;;7;8],   A=[:a,:b],   I=[:i,:j],   X=[:x,:y]   )



# proposed syntax
mapslices( my_func,  K;   dims=(:A) )

#would give the same result as 
@tullio Z[i,x] := my_func( (; slice=K[:,i,x], I=K.I[i], X=K.X[x])  )
KeyedArray( Z, I=K.I, X=K.X)
```

**Comment by Lincoln-Hannah** [comment]
I don't think I'm smart enough to build it myself.  Hence the request.

I previously requested similar functionality though based on the DataFramesMeta @rtransform macro. See my last post in https://github.com/mcabbott/AxisKeys.jl/issues/154     
(reading it now its not very clear sorry)

In both requests the idea is to select a dimension or dimensions to slice across, then have access to both the underlying data and index labels both within the slice and orthogonal to the slice.

**Comment by Lincoln-Hannah** [comment]
Genius thank you :)
I'll probably lay it out like this.

```
eachSliceKeys = with_axiskeys ∘ eachslice 

function my_func( ( (;I,X),  slice)::Pair{NamedTuple,KeyedArray} )  

    "$I  $X    $(slice(:a))"

end


K  =   KeyedArray(   [1;2;;3;4;;;5;6;;7;8],   A=[:a,:b],   I=[:i,:j],   X=[:x,:y]   )


@chain begin 
    K 
    eachSliceKeys(dims=(:I,:X))
    my_func.()
end
```

**Comment by Lincoln-Hannah** [comment]
Sorry, one more question.
If the slice function returns a KeyedArray, so the result is a nested KeyedArray,   is there an easy way to flatten it ?
i.e. convert it to a single level 3D KeyedArray.


function my_func2( ( (;I,X),  slice)::Pair{<:NamedTuple,<:KeyedArray} )  

    KeyedArray(  I .* [slice(:a),slice(:b)] , New=[:n1,:n2]  )

end


@chain begin 
    K 
    eachSliceKeys(dims=(:I,:X))    
    my_func2.()
end

**Comment by lincolnhannah** [comment]
Thanks:)
I saw stack after I'd posted the question.
Amazing.  One word solution!

**Comment by Lincoln-Hannah** [comment]
Is there any shorter way to do this ?

```
allMissing = isempty ∘ skipmissing 

KA = KeyedArray( [1 2 3;1 missing 3; missing missing missing], a=[:a,:b,:c], x=[:x,:y,:z])


@chain begin

     X

    eachslice( dims = :a )

    filter( !allMissing, _ )

    AxisKeys.stack

end
```

Something like    `filterslices(    X,   !allMissing,  dims  = :a  )`
