### ISSUE TITLE
License

### ISSUE THREAD

**Issue by visr** [mcabbott/AxisKeys.jl#16]
Hi, I just noticed there is no license in this repository. I guess this is an oversight? Otherwise it's under exclusive copyright by default (https://choosealicense.com/no-permission/).

I would suggest MIT like most other julia packages, and am ok with licensing my (tiny) contribution as MIT.

One easy way to do this is by filling in the repo url on the right hand side of https://choosealicense.com/licenses/mit/, under "Suggest this license".

BTW, I quickly went over a few of your other repos, and there are more with a missing license, e.g.:
https://github.com/mcabbott/Tullio.jl
https://github.com/mcabbott/LazyStack.jl
https://github.com/mcabbott/Bhaskara.jl
https://github.com/mcabbott/TransmuteDims.jl

**Comment by mcabbott** [comment]
Yes, just laziness -- the Project.toml does say MIT, but you are right that I should make a file.

**Comment by visr** [comment]
I see. I didn't look in the Project.toml. Thanks for fixing it in this repo.

Just checking the others again, I see these don't have a LICENSE and also no mention in the Project.toml.
https://github.com/mcabbott/Tullio.jl
https://github.com/mcabbott/Bhaskara.jl
https://github.com/mcabbott/TransmuteDims.jl

But since this concerns other repositories, feel free to close this issue.

**Comment by mcabbott** [comment]
I will fix the others eventually, when I get them into a releasable state. So for now I close this here.
