### ISSUE TITLE
matmul test fails on Julia 1.5

### ISSUE THREAD

**Issue by visr** [mcabbott/AxisKeys.jl#17]
In the list in https://github.com/JuliaCI/NanosoldierReports/blob/18bb6d85b20e25f1a9f2f312963f4b8b4fe7082e/pkgeval/by_hash/a340bf1_vs_3c50b7f/report.md I noticed AxisKeys tests are failing on julia 1.5.

Not sure if it is an AxisKeys or NamedDims issue, but here is the error: https://github.com/JuliaCI/NanosoldierReports/blob/18bb6d85b20e25f1a9f2f312963f4b8b4fe7082e/pkgeval/by_hash/a340bf1_vs_3c50b7f/logs/AxisKeys/1.5.0-DEV-fc8aa8666a.log#L140

**Comment by mcabbott** [comment]
Thanks, yes I took a quick look at this but didn't solve it. It might be enough to add one more specific `NamedDimsArray{...,KeyedArray{...}}` method here:

https://github.com/mcabbott/AxisKeys.jl/blob/f5d19aad2262386c22cdeb77dc685e1550bacd76/src/functions.jl#L247-L248

Of course my test just happened to hit this combination, ideally these would be made to work:
```julia
@test isempty(detect_unbound_args(AxisKeys))
@test isempty(detect_ambiguities(AxisKeys, Base))
```

**Comment by mcabbott** [comment]
I think this got fixed! Certainly tests pass.
