### ISSUE TITLE
Tables.columntable return value

### ISSUE THREAD

**Issue by bkamins** [mcabbott/AxisKeys.jl#23]
Normally I would assume that `Tables.columntable` would return a `NamedTuple` of `Tables.CopiedColumns` or a `NamedTuple` of `view`s (depending on your design assumptions).

Now it returns a `NamedTuple` of vectors which is a bit problematic, because downstream methods (in particular DataFrames.jl) do not know if upon creation of the object columns should be copied or not.

I think (but we can discuss) that it would be better to create a view, so that `Tables.columntable` is non-allocating. What do you think?

**Comment by mcabbott** [comment]
Thanks for taking a look, this is all very much a first attempt, and I'm sure it could be better. 

`Tables.columns`returns a view for the `:value` column, but the others it makes new arrays, as a comprehension using Iterators.product. Is there an obvious lazy object that could be used? From my comments it looks like (1) a generator is insufficient, and (2) I didn't want to depend on Kronecker.jl or something, just to get a lazy product.

**Comment by bkamins** [comment]
Given your comment I think you can leave things as-is, and we have to copy columns of this `NamedTuple` when creating a `DataFrame`.

A small note is that using `vec` it is non obvoius that you are sharing data with the source. Probably it would be good to document it (if it is not documented already).

From DataFrames.jl this issue can be closed (so I am closing it). Thank you!

**Comment by mcabbott** [comment]
Wait it seems like this ought to be consistent at least, and not make a view of just one column, without flagging things? If adding `Tables.CopiedColumns` would help that would be super-easy.

**Comment by bkamins** [comment]
I think `Tables.CopiedColumns` can be omitted - it was initially designed only for cases when `Tables.columntable` were intended to create only a temporary object.
