### ISSUE TITLE
Add an `align` function

### ISSUE THREAD

**Issue by rofinn** [mcabbott/AxisKeys.jl#33]
I'll open this as an issue first in case it exists and I couldn't find it. I'm looking for a function like xarrays `align` to be able to align the keys of multiple `KeyedArrays`. If this doesn't exist in some form then I'm happy to work on an implementation.

http://xarray.pydata.org/en/stable/generated/xarray.align.html?highlight=align#xarray-align

**Comment by mcabbott** [comment]
dup of #32?

**Comment by rofinn** [comment]
Oops, sorry, GitHub gave me a 404, so I assumed it didn't go through.
