### ISSUE TITLE
Feature request: Iterators.product

### ISSUE THREAD

**Issue by fredcallaway** [mcabbott/AxisKeys.jl#40]
It would be nice for Iterators.product applied to KeyedArrays to appropriately carry forward axis information. I am happy to make a pull request for this if there is interest. One design decision is how to handle the case where a KeyedArray is "producted" with a standard Array. I think dropping the keys in this case would make sense.

**Comment by mcabbott** [comment]
Would be nice to have, and probably not so difficult. NamedDims does this:
```
julia> [x//y for x in rand(Int8, row=3), y in 10:10:50]
3×5 NamedDimsArray(::Matrix{Rational{Int64}}, (:row, :_)):
        → :_
↓ :row  -81//10  -81//20  -27//10  -81//40  -81//50
        -49//10  -49//20  -49//30  -49//40  -49//50
         42//5    21//5    14//5    21//10   42//25
```
which it catches so long as one of the first two is named, here: https://github.com/invenia/NamedDims.jl/blob/942bb283c62dd64c0ca484bda19c1bb832f268fa/src/functions.jl#L187-L201

**Comment by fredcallaway** [comment]
The plot thickens.... for reasons I don't fully understand, we already get the desired behavior when mapping over the ProductIterator.

```
x = KeyedArray(1:.1:1.3, x=1:.1:1.3)
y = 1:3
z = KeyedArray(['a', 'b'], z=['a', 'b'])
map(identity, Iterators.product(x, y, z))      
```
produces
```                                                                               
3-dimensional KeyedArray(NamedDimsArray(...)) with keys:
↓   x ∈ 4-element StepRangeLen{Float64,...}
→   _ ∈ 3-element OneTo{Int}
□   z ∈ 2-element Vector{Char}
And data, 4×3×2 Array{Tuple{Float64,Int64,Char},3}:
[:, :, 1] ~ (:, :, 'a'):
        (1)               (2)               (3)
 (1.0)     (1.0, 1, 'a')     (1.0, 2, 'a')     (1.0, 3, 'a')
 (1.1)     (1.1, 1, 'a')     (1.1, 2, 'a')     (1.1, 3, 'a')
 (1.2)     (1.2, 1, 'a')     (1.2, 2, 'a')     (1.2, 3, 'a')
 (1.3)     (1.3, 1, 'a')     (1.3, 2, 'a')     (1.3, 3, 'a')

[:, :, 2] ~ (:, :, 'b'):
        (1)               (2)               (3)
 (1.0)     (1.0, 1, 'b')     (1.0, 2, 'b')     (1.0, 3, 'b')
 (1.1)     (1.1, 1, 'b')     (1.1, 2, 'b')     (1.1, 3, 'b')
 (1.2)     (1.2, 1, 'b')     (1.2, 2, 'b')     (1.2, 3, 'b')
 (1.3)     (1.3, 1, 'b')     (1.3, 2, 'b')     (1.3, 3, 'b')
```

This is enough for my use case. It would be nice if KeyedArray(Iterators.product(x, y, z)) worked as well though. Could that be accomplished using a similar method to the one you quoted from NamedDims?

**Comment by mcabbott** [comment]
Oh I guess I forgot that I implemented this! `@edit collect(x for x in Iterators.product(x, y, z))` is where this goes (for `map(f, ::Any)`, but generator syntax calls the same thing).

To make `KeyedArray(Iterators.product(x, y, z))` work just like that there would have to be one more method. Do you use it like this? I almost always either write the comprehension, or do something with the `x,y,z` before making the array.

**Comment by fredcallaway** [comment]
Haha, kind of like finding a $20 in your pocket!

Like you, I always immediately have a map over ProductIterator, so I don't think it's necessary to have the KeyedArray method. The only reason to implement it is for aesthetics, probably not worth either of our time :P

Thanks for the quick response and the awesome package!
