### ISSUE TITLE
Keep lazy loading of data in mind?

### ISSUE THREAD

**Issue by maxfreu** [mcabbott/AxisKeys.jl#51]
Hi, just a short notice & a thing one might keep in mind: In case this package is used to wrap some sort of disk-backed array which supports lazy loading, the show function loads eagerly from disk which can be a problem for big datasets. See  https://github.com/rafaqz/GeoData.jl/issues/89

**Comment by mcabbott** [comment]
It does try to get only the values to be printed (or a few more), in the making of `fakearray` here:
https://github.com/mcabbott/AxisKeys.jl/blob/master/src/show.jl#L80-L103
Do you think it ought to be further restricted somehow? Can it detect when this is or isn't going to be a problem?

**Comment by maxfreu** [comment]
I typed so much text and now it jumped at me:
https://github.com/mcabbott/AxisKeys.jl/blob/master/src/show.jl#L84
is missing a `size(A,2)-...`! So it tries to get almost eeeeeverything along dim 2 ;-)

Also ind1 is one larger than h for even h I think, but thats maybe not so important.

**Comment by mcabbott** [comment]
Oh well spotted, sorry about that. The intent was there!

**Comment by maxfreu** [comment]
Hmmm something more is fishy here. I fixed it locally, but still get OOM errors. Probably the underlying driver is trying to load all the data in, since everything is bundled in one getindex call. So maybe one could split it up into four calls manually and reassemble it.
