### ISSUE TITLE
view doesn't support indexing by key

### ISSUE THREAD

**Issue by glennmoy** [mcabbott/AxisKeys.jl#68]
For instance, we can `view` a KeyedArray by passing in the appropriate indices, but if we wanted to use the corresponding `keys` instead that isn't possible. Of course, calling `KA(:a)` is quite convenient but `Base.view` is often called in packages that expect an `AbstractArray`, so it would be nice if that was compatible with passing in keys instead of indices.

```
julia> KA = KeyedArray(rand(3, 5), features=[:a, :b, :c], time=1:5);

julia> view(KA, 1, :)
1-dimensional KeyedArray(NamedDimsArray(...)) with keys:
↓   time ∈ 5-element UnitRange{Int64}
And data, 5-element view(::Matrix{Float64}, 1, :) with eltype Float64:
 (1)  0.4641547335476697
 (2)  0.739015103011146
 (3)  0.34302619878129414
 (4)  0.9326806444048761
 (5)  0.645438413359315

julia> view(KA, :a, :)
ERROR: ArgumentError: invalid index: :a of type Symbol
Stacktrace:
 [1] to_index(i::Symbol)
   @ Base ./indices.jl:300
 [2] to_index(A::KeyedArray{Float64, 2, NamedDimsArray{(:features, :time), Float64, 2, Matrix{Float64}}, Tuple{Vector{Symbol}, UnitRange{Int64}}}, i::Symbol)
   @ Base ./indices.jl:277
 [3] to_indices
   @ ./indices.jl:333 [inlined]
 [4] to_indices
   @ ./indices.jl:324 [inlined]
 [5] view(::KeyedArray{Float64, 2, NamedDimsArray{(:features, :time), Float64, 2, Matrix{Float64}}, Tuple{Vector{Symbol}, UnitRange{Int64}}}, ::Symbol, ::Function)
   @ AxisKeys ~/.julia/packages/AxisKeys/VS8DQ/src/struct.jl:75
 [6] top-level scope
   @ REPL[73]:1

```

**Comment by mcabbott** [comment]
This won't work for the same reason that `KA[:a, :]` doesn't --- this package's worldview is that `:a` is not an index, and operations looking up what index it corresponds to are always distinct, so that even if keys & indices are both integers, everything is unambiguous.

What does work however is `KA[Key(:a), :]`, or `view(KA, Key(:a), :)`.

**Comment by glennmoy** [comment]
> operations looking up what index it corresponds to are always distinct, so that even if keys & indices are both integers, everything is unambiguous.
> What does work however is `KA[Key(:a), :]`, or `view(KA, Key(:a), :)`.

Ah I see, that makes sense then. Thanks, this was helpful.
