### ISSUE TITLE
Support for GPU Arrays?

### ISSUE THREAD

**Issue by ParadaCarleton** [mcabbott/AxisKeys.jl#71]
Is it possible to use AxisKeys.jl together with GPU arrays, e.g. those in KernelAbstractions.jl or CUDA.jl?

**Comment by ParadaCarleton** [comment]
Yes.

**Comment by mcabbott** [comment]
OK! 

The package's approach is always to un-wrap, call whatever function on the parent array, and then re-wrap. So if the parent is a CuArray, this may just work. But nothing is explicitly tested against this, and there may be unexpected bugs.
