### ISSUE TITLE
Unable to Index into AxisKeys from Inside Package

### ISSUE THREAD

**Issue by ParadaCarleton** [mcabbott/AxisKeys.jl#72]
I consistently get the following error when I try to load a package that uses AxisKeys:

```
ERROR: LoadError: LoadError: syntax: ":Estimate" is not a valid function argument name around /home/lime/.julia/dev/ParetoSmooth/src/LeaveOneOut.jl:69
```

The relevant code snippet is here:
```
    tbl = KeyedArray(similar(log_likelihood, 3, 2); 
        crit=[:loo, :p_loo, :loo_ic],
        est=[:Estimate, :SE],
        )
    
    # Use Bayesian bootstrap to build confidence intervals
    tbl(:Estimate, :loo) = mean(pointwise_ev)
    tbl(:Estimate, :p_loo) = sum(pointwise_p_eff)
    tbl(:Estimate, :loo_ic) = -2 * ev_loo

    tbl(:SE, :loo) = se = sqrt(varm(pointwise_ev, ev_loo) / data_size)
    tbl(:SE, :p_loo) = sqrt(varm(pointwise_p_eff, p_eff / data_size) * data_size)
    tbl(:SE, :loo_ic) = 2 * se
```
Neither lookup with parentheses, nor indexing with square brackets, works.  Replacing parentheses with square brackets instead results in `ERROR: ArgumentError: invalid index: :Estimate of type Symbol` when running the code.

**Comment by mcabbott** [comment]
This is the downside of the "round brackets do lookup, square brackets do indexing" scheme -- because this is parsed as function definition, not a kind of `setindex!`, and can't be overloaded. 

Some possible but not so pretty workarounds are:
```
tbl(:Estimate, :loo, :) .= mean(pointwise_ev)  # make a view
tbl[Key(:Estimate), Key(:loo)] = mean(pointwise_ev)  # use setindex!
```

**Comment by ParadaCarleton** [comment]
> This is the downside of the "round brackets do lookup, square brackets do indexing" scheme -- because this is parsed as function definition, not a kind of `setindex!`, and can't be overloaded.
> 
> Some possible but not so pretty workarounds are:
> 
> ```
> tbl(:Estimate, :loo, :) .= mean(pointwise_ev)  # make a view
> tbl[Key(:Estimate), Key(:loo)] = mean(pointwise_ev)  # use setindex!
> ```

Is there another way to do lookups? Worth noting that the first suggestion didn't work -- I still got the same error about methods.

**Comment by mcabbott** [comment]
Oh, it's backwards, the order needs to match the definition. But that gives a different error:
```
julia> tbl(:Estimate, :loo, :) .= 0
ERROR: ArgumentError: could not find key :Estimate in vector [:loo, :p_loo, :loo_ic]

julia> tbl(:loo, :Estimate, :) .= 99  # note the .=
0-dimensional view(::Matrix{Float64}, 1, 1) with eltype Float64:
99.0
```
I agree it's a bit awkward, but I'm not so sure a macro is going to make this simpler. It could simply guess whether to index or lookup, and for Symbols this is not very confusing -- this is the line taken by other packages, but this one is a bit of an experiment to see if you can keep them more separate.
