### ISSUE TITLE
Feature request: column/row lookup with `.` syntax

### ISSUE THREAD

**Issue by ParadaCarleton** [mcabbott/AxisKeys.jl#74]
I believe defining a `getproperty` method for KeyedArrays which looks up a column/row and then returns it should be enough for this to work.

**Comment by rofinn** [comment]
I think this would be ill-advised since `getproperty` only makes sense for symbol lookups and there isn't any such requirement for the keys of a `KeyedArray`. Using `getproperty` to access all keys along a dimension make sense to me because we've restricted the dimnames to symbols via NamedDims.jl.

**Comment by mcabbott** [comment]
There is a `getproperty` method, but what it does is this:
```julia
ka = wrapdims(rand(Int8,3,5), channel=[:r, :g, :b], time=0.1:0.1:5)
for t in ka.time
    @show ka(time=t)
end
```
I think you're proposing making `ka(:r) == ka.r`. This is not impossible, but conflicts a bit with the package's attempt not to be neutral about types -- it's very specific to arrays with one vector of symbols attached. While `ka("r")` would work if I had `channel = ["r", "g", "b"]`.

**Comment by ParadaCarleton** [comment]
Makes sense, thanks for letting me know.
