### ISSUE TITLE
consider a character other than `□` to label 3rd dimension

### ISSUE THREAD

**Issue by kleinschmidt** [mcabbott/AxisKeys.jl#82]
Every time I see `□` I think "oh a unicode character that my font is missing a glyph for", even though I know at an intellectual level it's referring to the "sheets" of the array.  I'm not sure there's a better option though.  @ericphanson suggested that `↗` might work since it's "going off in another direction", or alteratively that we "choose a random arrow from https://www.sascha-frank.com/Arrow/latex-arrows.html every time"

**Comment by mcabbott** [comment]
Yes I can see that, sorry! Something grid-like such as `⊞` or `▦` or `▨` might convey this with less surprise? Unicode doesn't seem to have a 3D cube... but does have many weird arrows like `↬`, `↯`, `⇲`.

Should the 4th differ from the 3rd?

**Comment by kleinschmidt** [comment]
1. Petition unicode consortium to add TimeCube
2. ...
3. Profit?

I think any of the grid-like would be good, as well as ❒.  I think if you wanted to have a different symbol for 3rd and 4th axis, I'd pick ▨ for 3rd (just because crosshatching is fun) and ❒ for 4th (since it's got a "brick" flavor).
