### ISSUE TITLE
Unable to index KeyedArray of arrays

### ISSUE THREAD

**Issue by aplavin** [mcabbott/AxisKeys.jl#83]
MWE:
```julia
ka = KeyedArray(fill([], (1, 1)), a=1:1, b=1:1)

first(ka)
#or
ka[1]
# throw an error:
MethodError: no method matching keys_getindex(::Tuple{UnitRange{Int64}}, ::Tuple{})
Closest candidates are:
keys_getindex(!Matched::Tuple{}, ::Tuple{}) at /home/aplavin/.julia/packages/AxisKeys/MhCtB/src/struct.jl:123
keys_getindex(::Tuple, !Matched::Tuple{Base.Slice, Vararg{Any}}) at /home/aplavin/.julia/packages/AxisKeys/MhCtB/src/struct.jl:100
keys_getindex(::Tuple, !Matched::Tuple{AbstractVector{CartesianIndex{0}}, Vararg{Any}}) at /home/aplavin/.julia/packages/AxisKeys/MhCtB/src/struct.jl:114
...
keys_getindex@struct.jl:96[inlined]
getindex(::AxisKeys.KeyedArray{Vector{Any}, 2, NamedDims.NamedDimsArray{(:a, :b), Vector{Any}, 2, Matrix{Vector{Any}}}, Tuple{UnitRange{Int64}, UnitRange{Int64}}}, ::Int64)@struct.jl:80
```
It works when eltype is not an array itself, e.g. with `ka = KeyedArray(fill(1, (1, 1)), a=1:1, b=1:1)`.

As I understand, the bug is caused by this check: https://github.com/mcabbott/AxisKeys.jl/blob/24b89d51f6262bb512abebb4b8e6d106e3acc87b/src/struct.jl#L78. Is it possible to make checks more general here?

**Comment by mcabbott** [comment]
Good catch, that check is indeed too naiive, and will fail for arrays of arrays. 

I wonder why it doesn't check `inds isa Tuple{Vararg{Integer}}`? Perhaps I was trying to allow for zero-dimensional views like `view([0,pi], 2)`, although arguably not wrapping those would make a lot of sense.

**Comment by aplavin** [comment]
With rich indexing behaviors of Julia, I cannot really tell the proper general way to check whether provided indices correspond to a scalar result. Base doesn't seem to provide helper functions either...
