### ISSUE TITLE
Move to Org / Give more people merge rights

### ISSUE THREAD

**Issue by oxinabox** [mcabbott/AxisKeys.jl#86]
@mcabbott  and I talked about this on slack.
Either moving this package to an org, and/or giving @rofinn  merge rights (he is second biggest contributor).
Transferring it to an issue as it is about to go into the slack memory hole.

**Comment by oxinabox** [comment]
Bump

**Comment by mcabbott** [comment]
We should do this, I'm sorry about the delay. 

For now I've invited @rofinn, I'm not an expert on permission levels but I think I put you both in the same box.

You could talk me into moving it. I don't think I am in any suitable organisation. It seems a little odd for JuliaArrays to contain "competing products" but maybe not the first time (and a bit of a sad outcome that we ended up there at all...).
